name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install devkitPro
      run: |
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        rm install-devkitpro-pacman
        . /etc/profile.d/devkit-env.sh
        sudo dkp-pacman -Syy --noconfirm
        sudo dkp-pacman -S 3ds-dev --noconfirm
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: "recursive"
    - name: Make
      run: make
    - name: Upload output/ directory
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: output/
